openapi: 3.0.1
info:
  title: Cisco Umbrella Reporting API
  description: |-
    The Reporting API provides the data to generate the Umbrella reports.
  version: 2.0.0
  contact:
    name: Cloud Security Developer Community
servers:
  - url: https://api.umbrella.com/{basePath}
    variables:
      basePath:
        default: reports/v2
tags:
  - name: Activity
  - name: Top Identities
  - name: Identity Distribution
  - name: Top Destinations
  - name: Top Categories
  - name: Top Event Types
  - name: Top DNS Query Types
  - name: Organization Requests by Hour
  - name: Organization Requests by Timerange
  - name: Organization Requests by Hour and Category
  - name: Organization Requests by Timerange and Category
  - name: Deployment Status
  - name: Provider Deployment Status
  - name: Provider Requests by Hour
  - name: Provider Requests by Timerange
  - name: Provider Requests by Organization
  - name: Provider Requests by Category
  - name: Provider Requests by Destination
  - name: Provider Category Requests by Organization
  - name: Bandwidth by Hour
  - name: Bandwidth by Timerange
  - name: Top Files
  - name: Total Requests
  - name: Top Threats
  - name: Top Threat Types
  - name: Utility
  - name: Top IPs
  - name: Summary
  - name: Summaries by Category
  - name: Summaries by Destination
  - name: Summaries by Rule (Intrusion)
  - name: Umbrella

security:
  - oauthFlow: []

paths:
  /activity:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activities (All)
      description: |-
        List all activities (dns/proxy/firewall/intrusion) within the timeframe.
        **Note:** The IP activity report is not available.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivities
      security:
        - oauthFlow:
          - reports.aggregations:read
  /activity/dns:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity DNS
      description: |-
        List all DNS entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityDns
      security:
        - oauthFlow:
          - reports.aggregations:read
  /activity/proxy:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity Proxy
      description: |-
        List all proxy entries within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityProxy
      security:
        - oauthFlow:
          - reports.aggregations:read
  /activity/firewall:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity Firewall
      description: |-
        List all firewall activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityFirewall
      security:
        - oauthFlow:
          - reports.aggregations:read
  /activity/intrusion:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity Intrusion
      description: |-
        List all Intrusion Prevention System (IPS) activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityIntrusion
      security:
        - oauthFlow:
          - reports.aggregations:read
  # deprecated IP Enforcement Layer
  /activity/ip:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity IP
      description: |-
        (Deprecated) List all IP activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityIP
      security:
        - oauthFlow:
          - reports.aggregations:read
  /activity/amp-retrospective:
    get:
      tags:
        - Activity
        - Umbrella
      summary: Get Activity AMP Retrospective
      description: |-
        List all AMP retrospective activity within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getActivityAmpRetrospective
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-identities:
    get:
      tags:
        - Top Identities
        - Umbrella
      summary: Get Top Identities (All)
      description: |-
        List the identities by the number of requests made, sorted in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentities
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-identities/{type}:
    get:
      tags:
        - Top Identities
        - Umbrella
      summary: Get Top Identities
      description: |-
        List the identities for the specific traffic type by the number of requests.
        Sort the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentitiesType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /identity-distribution:
    get:
      tags:
        - Identity Distribution
        - Umbrella
      summary: Get Identity Distribution (All)
      description: |-
        List the number of requests by identity types.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistribution
      security:
        - oauthFlow:
          - reports.aggregations:read
  /identity-distribution/{type}:
    get:
      tags:
        - Identity Distribution
        - Umbrella
      summary: Get Identity Distribution By Type
      description: |-
        List the number of requests by identity for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistributionType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-destinations:
    get:
      tags:
        - Top Destinations
        - Umbrella
      summary: Get Top Destinations
      description: |-
        List the destinations by the number of requests made to this destination.
        Return the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinations
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-destinations/{type}:
    get:
      tags:
        - Top Destinations
        - Umbrella
      summary: Get Top Destinations By Type
      description: |-
        List the destinations by type of destination and the number of requests made
        to this destination. Return the collection in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinationsType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-urls:
    get:
      tags:
        - Top Destinations
        - Umbrella
      summary: Get Top URLs
      description: |-
        List the top number of URLs that are requested for a certain domain.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopUrls
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-categories:
    get:
      tags:
        - Top Categories
        - Umbrella
      summary: Get Top Categories (All)
      description: |-
        List the categories that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategories
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-categories/{type}:
    get:
      tags:
        - Top Categories
        - Umbrella
      summary: Get Top Categories By Type
      description: |-
        List the categories for the type of traffic that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategoriesType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-eventtypes:
    get:
      tags:
        - Top Event Types
        - Umbrella
      summary: Get Top Event Types (All)
      description: |-
        List the top event types by the number of requests made for each type of event.
        Order the number of requests in descending order.
        The valid event types are: `domain_security`, `domain_integration`,
        `url_security`, `url_integration`, `cisco_amp`, and `antivirus`.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopEventTypes
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-dns-query-types:
    get:
      tags:
        - Top DNS Query Types
        - Umbrella
      summary: Get Top DNS Query Types
      operationId: getTopDNSQueryTypes
      description: |-
        List the top types of DNS query.

        **Access Scope:** Reports > Aggregations > Read-Only
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-by-hour:
    get:
      tags:
        - Organization Requests by Hour
        - Umbrella
      summary: Get Requests by Hour (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHour
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /requests-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour
        - Umbrella
      summary: Get Requests by Hour
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getOrganizationRequestsByHour
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /requests-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange
        - Umbrella
      summary: Get Requests by Timerange (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerange
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /requests-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange
        - Umbrella
      summary: Get Requests by Timerange
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeType
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /categories-by-hour:
    get:
      tags:
        - Organization Requests by Hour and Category
        - Umbrella
      summary: Get Requests by Hour and Category (All)
      description: |-
        List the activity volume within the timeframe by type of category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHourAndCategory
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /categories-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour and Category
        - Umbrella
      summary: Get Requests by Hour and Category
      description: |-
        List the activity volume for the type of category within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByHourAndCategoryAndType
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /categories-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange and Category
        - Umbrella
      summary: Get Requests by Timerange and Category (All)
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeAndCategory
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /categories-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange and Category
        - Umbrella
      summary: Get Requests by Timerange and Category
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getRequestsByTimerangeAndCategoryType
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /deployment-status:
    get:
      tags:
        - Deployment Status
        - Umbrella
      summary: Get Deployment Status
      description: |-
        List the deployment status within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getDeploymentStatus
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /bandwidth-by-hour:
    get:
      tags:
        - Bandwidth by Hour
        - Umbrella
      summary: Get Bandwidth by Hour (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getBandwidthByHour
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /bandwidth-by-timerange:
    get:
      tags:
        - Bandwidth by Timerange
        - Umbrella
      summary: Get Bandwidth by Timerange (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getBandwidthByTimerange
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /top-files:
    get:
      tags:
        - Top Files
        - Umbrella
      summary: Get Top Files (Proxy)
      description: |-
        List the top files within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopFilesProxy
      security:
        - oauthFlow:
          - reports.aggregations:read
  /total-requests:
    get:
      tags:
        - Total Requests
        - Umbrella
      summary: Get Total Requests (All)
      description: |-
        Get the count of the total requests.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequests
      security:
        - oauthFlow:
          - reports.aggregations:read
  /total-requests/{type}:
    get:
      tags:
        - Total Requests
        - Umbrella
      summary: Get Total Requests (By Type)
      description: |-
        Get the count of the total requests for the request type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequestsByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threats:
    get:
      tags:
        - Top Threats
        - Umbrella
      summary: Get Top Threats (All)
      description: |-
        Get the top threats within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreats
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threats/{type}:
    get:
      tags:
        - Top Threats
        - Umbrella
      summary: Get Top Threats (By Type)
      description: |-
        Get the top threats within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatsByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threat-types:
    get:
      tags:
        - Top Threat Types
        - Umbrella
      summary: Get Top Threat Types (All)
      description: |-
        List the top types of threat within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypes
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threat-types/{type}:
    get:
      tags:
        - Top Threat Types
        - Umbrella
      summary: Get Top Threat Types By Type
      description: |-
        List the top threat-types within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypesByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /applications:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Applications
      operationId: getApplications
      description: |-
        List the applications.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
          - reports.utilities:read
  /categories:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Categories
      description: |-
        List the categories.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getCategories
      security:
        - oauthFlow:
          - reports.utilities:read
  /identities:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Identities
      operationId: getIdentities
      description: |-
        List the identities.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
          - reports.utilities:read
    post:
      tags:
        - Utility
        - Umbrella
      summary: Get Identities By IDs
      description: |-
        Get the identities information by providing a list of identity IDs in the request body.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: postIdentities
      security:
        - oauthFlow:
          - reports.utilities:read
  /identities/{identityid}:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Identity
      description: |-
        Get identity by identity ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getIdentity
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-types:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Threat Types
      description: |-
        List the threat types.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatTypes
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-types/{threattypeid}:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Threat Type By Threat ID
      description: |-
        List the threat types by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatType
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-names:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Threat Names
      description: |-
        List the threat names.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatNames
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-names/{threatnameid}:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Threat Name By Threat ID
      description: |-
        Get the threat name by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatName
      security:
        - oauthFlow:
          - reports.utilities:read
  /top-ips:
    get:
      tags:
        - Top IPs
        - Umbrella
      summary: Get Top IPs
      description: |-
        List the top IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIps
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-ips/internal:
    get:
      tags:
        - Top IPs
        - Umbrella
      summary: Get Top IPs Internal
      description: |-
        List the top internal IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIpsInternal
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summary:
    get:
      tags:
        - Summary
        - Umbrella
      summary: Get Summary (All)
      description: |-
        Get the summary report.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummary
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summary/{type}:
    get:
      tags:
        - Summary
        - Umbrella
      summary: Get Summary By Type
      description: |-
        Get the summary of requests by the traffic type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummaryByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-category:
    get:
      tags:
        - Summaries by Category
        - Umbrella
      summary: Get Summaries by Category (All)
      description: |-
        List the summaries of requests by category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategory
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-category/{type}:
    get:
      tags:
        - Summaries by Category
        - Umbrella
      summary: Get Summaries by Category For Type
      description: |-
        List the summaries by category for the type of request.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategoryType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-destination:
    get:
      tags:
        - Summaries by Destination
        - Umbrella
      summary: Get Summaries by Destination (All)
      description: |-
        List the summaries by destination.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestination
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-destination/{type}:
    get:
      tags:
        - Summaries by Destination
        - Umbrella
      summary: Get Summaries by Destination For Type
      description: |-
        List the summaries by destination for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestinationType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-rule/intrusion:
    get:
      tags:
        - Summaries by Rule (Intrusion)
        - Umbrella
      summary: Get Summaries by Rule
      description: |-
        List the summaries by rule for the intrusion type.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleIntrusion
      security:
        - oauthFlow:
          - reports.summariesByRule:read
  /providers/categories:
    get:
      tags:
        - Utility
        - Umbrella
      summary: Get Provider Categories
      description: |-
        List the Provider categories

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderCategories
      security:
        - oauthFlow:
          - reports.utilities:read
  /providers/deployments:
    get:
      tags:
        - Provider Deployment Status
        - Umbrella
      summary: Get Deployment Status by Organization
      description: |-
        List the summary counts of deployment status for the organization within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getDeploymentStatusByOrganization
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/requests-by-hour:
    get:
      tags:
        - Provider Requests by Hour
        - Umbrella
      summary: Get Provider Requests by Hour (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderRequestsByHour
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/requests-by-timerange:
    get:
      tags:
        - Provider Requests by Timerange
        - Umbrella
      summary: Get Provider Requests by Timerange (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderRequestsByTimerange
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/requests-by-org:
    get:
      tags:
        - Provider Requests by Organization
        - Umbrella
      summary: Get Provider Requests by Organization
      description: |-
        List the summary counts of all requests within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderRequestsByOrganization
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/requests-by-category:
    get:
      tags:
        - Provider Requests by Category
        - Umbrella
      summary: Get Provider Requests by Category
      description: |-
        List the summary counts of all requests within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderRequestsByCategory
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/requests-by-destination:
    get:
      tags:
        - Provider Requests by Destination
        - Umbrella
      summary: Get Provider Requests by Destination
      description: |-
        List the summary counts of all requests within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderRequestsByDestination
      security:
        - oauthFlow:
          - reports.customers:read
  /providers/category-requests-by-org:
    get:
      tags:
        - Provider Category Requests by Organization
        - Umbrella
      summary: Get Provider Category Requests by Organization
      description: |-
        List the summary counts of all requests for each category within the timeframe.

        **Access Scope:** Reports > Customer > Read-Only
      operationId: getProviderCategoryRequestsByOrganization
      security:
        - oauthFlow:
          - reports.customers:read
#  /cloud-malware:
#    get:
#      tags:
#        - Cloud Malware
#      summary: Get Cloud Malware Events
#      description: List the events logged by Cloud Malware.
#      operationId: getCloudMalwareEvents
#      security:
#        - oauthFlow:
#          - reports.aggregations:read
#      parameters:
#        - $ref: '#/components/parameters/fromParam'
#        - $ref: '#/components/parameters/toParam'
#        - $ref: '#/components/parameters/limitParam'
#        - $ref: '#/components/parameters/timezoneParam'
#      responses:
#        '200':
#          description: OK
#          content:
#            application/json:
#              schema:
#               type: object
#                properties:
#                  data:
#                    type: array
#                    items:
#                      $ref: '#/components/schemas/CloudMalware'
#                  meta:
#                    $ref: '#/components/schemas/Meta'
#                required:
#                  - data
#                  - meta
#              example:
#                data: []
#                meta: {}
#        '400':
#          $ref: '#/components/responses/400Error'
#        '401':
#          $ref: '#/components/responses/401Error'
#        '403':
#          $ref: '#/components/responses/403Error'
#        '404':
#          $ref: '#/components/responses/404Error'
#        '500':
#          $ref: '#/components/responses/500Error'

components:

# duplicate with RequestsbyHour
#    ProviderRequestsByHour:
#      type: object
#      description: The information about the provider's requests by hour
#      properties:
#        counts:
#          properties:
#            requests:
#              type: number
#              description: total number of requests
#            allowedrequests:
#              type: number
#              description: number of requests that were allowed
#              nullable: true
#            blockedrequests:
#              type: number
#              description: number of requests that were blocked
#              nullable: true
#          required:
#            - requests
#            - allowedrequests
#            - blockedrequests
#        count:
#          type: number
#        date:
#          $ref: '#/components/schemas/Date'
#        time:
#          $ref: '#/components/schemas/Time'
#        timestamp:
#          $ref: '#/components/schemas/TimestampForBucket'
#      required:
#        - count
#        - date
#        - time
#        - timestamp
#      example:
#        counts:
#          requests: 123
#          allowedrequests: 60
#          blockedrequests: 63
#        count: 0
#        date: '2020-04-01'
#        time: '05:00:00'
#        timestamp: 1585717200000
    ProviderCountsByCategory:
      type: object
      description: The information about the provider's categories.
      properties:
        total:
          type: number
          description: The total number of requests.
        totalblocked:
          type: number
          description: The total number of blocked requests.
        numberoforganizationsaffected:
          type: number
          description: The number of organizations with traffic for that category.
      required:
        - numberoforganizationsaffected
        - total
        - totalblocked
    ProviderCountsByDestination:
      type: object
      description: The information about the provider's destinations.
      properties:
        total:
          type: number
          description: The total number of requests.
        totalblocked:
          type: number
          description: The total number of blocked requests.
        numberoforganizationsaffected:
          type: number
          description: The number of organizations with traffic for that category.
      required:
        - numberoforganizationsaffected
        - total
        - totalblocked
    ProviderDeploymentStatus:
      type: object
      description: The information about the provider's deployment status.
      properties:
        identitytype:
          $ref: '#/components/schemas/IdentityType'
        activecount:
          type: number
          description: The number of active identity types.
        count:
          type: number
          description: The total number of identity type.
      required:
        - activecount
        - count
        - identitytype
    CategoryRequests:
      type: object
      description: The information about categories and requests.
      properties:
        category:
          $ref: '#/components/schemas/Category'
        requests:
          type: number
          description: The number of requests.
        requestsblocked:
          type: number
          description: The number of requests that were blocked.
        numberoforganizationswithcategorizedtraffic:
          type: number
          description: The number of organizations with traffic for that category.
    DataCenter:
      type: object
      description: The information about the data center.
      properties:
        id:
          type: string
          description: The unique ID for the data center.
        label:
          type: string
          description: The name of the data center.
      required:
        - id
        - label
    DataLossPreventionState:
      type: object
      description: The information about the Data Loss Prevention state.
      properties:
        state:
          type: string
          description: Indicates the status of the DLP. The state is either `blocked` or the empty string (` `).
          enum: [blocked, '']
      required:
        - state
    DeploymentStatus:
      type: object
      description: The information about the deployment status.
      properties:
        type:
          $ref: '#/components/schemas/IdentityType'
        activecount:
          type: number
          description: The count of the active identity type.
        count:
          type: number
          description: The total count of the identity type.
      required:
        - activecount
        - count
        - type
    Egress:
      type: object
      description: The information about the egress IP.
      properties:
        ip:
          type: string
          description: The egress IP.
        type:
          type: string
          description: The type of the egress IP.
      required:
        - ip
        - type
    TopIP:
      type: object
      description: The information about the top IP addresses.
      properties:
        ip:
          type: string
          description: The comma-delimited list of IP addresses.
        count:
          type: number
          description: The number of requests to the top IP addresses.
      required:
        - count
        - ip
    RequestCounts:
      type: object
      description: The information about the requests.
      properties:
        requests:
          type: number
          description: The total number of requests.
        allowedrequests:
          type: number
          description: The number of requests that were allowed.
        blockedrequests:
          type: number
          description: The number of requests that were blocked.

    requests:
      type: number
      description: The total number of requests.

    TopDnsQueryType:
      type: object
      description: The information about the top DNS queries.
      properties:
        requests:
          $ref: '#/components/schemas/requests'
        querytype:
          type: string
          description: The type of the DNS query.
      required:
        - querytype
        - requests
    count:
      type: number
      description: The total number of requests.

    TopURL:
      type: object
      description: The information about the top URLs.
      properties:
        count:
          $ref: '#/components/schemas/count'
        path:
          type: string
          description: The URL path.
        categories:
          $ref: '#/components/schemas/categories'
        rank:
          type: number
          description: The numeric rank of the top URL.
      required:
        - categories
        - count
        - path
        - rank
    TotalRequest:
      type: object
      description: The total number of requests.
      properties:
        count:
          $ref: '#/components/schemas/count'
      required:
        - count
    SummaryWithCategory:
      type: object
      description: The properties of the category and summary.
      properties:
        category:
          $ref: '#/components/schemas/Category'
        summary:
          $ref: '#/components/schemas/Summary'
      required:
        - category
        - summary
    SummaryWithDestination:
      type: object
      description: The summary and destination information.
      properties:
        domain:
          type: string
          description: destination domain
        summary:
          $ref: '#/components/schemas/Summary'
      required:
        - domain
        - summary
    SignatureListSummary:
      type: object
      description: The summary information about the signature lists.
      properties:
        signaturelist:
          $ref: '#/components/schemas/SignatureList'
        signatures:
          type: array
          description: The list of information about the signatures.
          items:
            type: object
            properties:
              generatorid:
                type: number
                description: The generator ID of the signature.
              id:
                type: number
                description: The ID of the signature.
              lasteventat:
                type: number
                description: The date and time in milliseconds of the last event.
              counts:
                type: object
                properties:
                  blocked:
                    type: number
                    description: The number of blocked signatures.
                  detected:
                    type: number
                    description: The number of detected signatures.
                  wouldblock:
                    type: number
                    description: The number of signatures to block.
                required:
                  - blocked
                  - detected
                  - wouldblock
        rule:
          $ref: '#/components/schemas/RuleParam'
    ThreatType:
      type: object
      description: The properties of the threat type.
      properties:
        name:
          type: string
          description: The name of the threat type.
        description:
          type: string
          description: The name of the threat type.
      required:
        - name
        - description
    ThreatName:
      type: object
      description: The properties of the threat name.
      properties:
        name:
          type: string
          description: The name of the threat.
        description:
          type: string
          description: The description of the threat name.
      required:
        - name
        - description
    Policy:
      type: object
      description: The properties of the rules in the policy.
      required:
        - destinationlistids
        - ruleid
        - rulesetid
        - timebasedrule
      properties:
        timebasedrule:
          type: boolean
          description: Specify whether the policy triggered a time-of-day rule.
        destinationlistids:
          type: array
          description: The list of destination lists that the rules triggered.
          items:
            type: number
        ruleid:
          type: number
          description: The ID of the rule in the policy.
          nullable: true
        rulesetid:
          type: number
          description: The ID of the ruleset in the policy.
          nullable: true
    HttpError:
      type: object
      description: The properties of the HTTP error.
      properties:
        type:
          type: string
          description: The type of the error, either `CertificateError` or `TLSError`.
          enum: [CertificateError, TLSError]
        code:
          type: number
          description: The HTTP error code.
        reason:
          type: string
          description: The name of the error.
        attributes:
          type: object
          description: The properties of the additional information for the error.

    Isolated:
      type: object
      description: The properties of the isolated file.
      properties:
        state:
          type: string
          description: The state of the isolated file.
        fileaction:
          type: string
          description: The action taken for the file.
      required:
        - state
        - fileaction
    Meta:
      type: object
      description: The properties of the metadata.
    Signature:
      type: object
      description: The properties of the signature.
      properties:
        generatorid:
          type: number
          description: The unique ID that is assigned to the part of the IPS, which generated the event.
        id:
          type: number
          description: The ID that is used to uniquely identify signatures.
        label:
          type: string
          description: A descriptive label for the the signature.
        cves:
          type: array
          description: The list of common vulnerabilites and exposures (CVEs).
          items:
            $ref: '#/components/schemas/CVE'
      required:
        - generatorid
        - id
        - label
        - cves
    SignatureList:
      type: object
      description: The properties of the signature list.
      properties:
        id:
          type: number
          description: The unique ID assigned to a default or custom signature list.
      required:
        - id
    RuleParam:
      type: object
      description: The properties of the rule parameter.
      properties:
        id:
          type: number
          description: The ID of the ruleset for the signature.
    Classification:
      type: string
      description: The category of attack detected by a rule that is part of a more general type of attack class, such as trojan-activity, attempted-user, and unknown.
    CVE:
      type: string
      description: An identifier for a known security vulnerability/exposure.
    Date:
      type: string
      description: The date from the timestamp based on the timezone parameter.
    DestinationIp:
      type: string
      description: The destination IP for the entry.
    DestinationPort:
      type: number
      description: The destination port for entry.
    SessionId:
      type: number
      description: The unique identifier of a session, which is used to group the correlated events between various services.
    Severity:
      type: string
      description: The severity level of the rule.
    #Valid values are: `High`, `Medium`, `Low`, and `Very Low`.
      enum: [HIGH, MEDIUM, LOW, VERY LOW]
    SourceIp:
      type: string
      description: The source IP for the entry.
    SourcePort:
      type: number
      description: The source port for the entry.
    Time:
      type: string
      description: The time in 24-hour format based on the timezone parameter.
    Timestamp:
      type: number
      description: The timestamp represented in milliseconds.
    TimestampInSeconds:
      type: number
      description: The timestamp represented in seconds.
    TimestampForBucket:
      type: number
      description: The timestamp represented in milliseconds for the bucket.
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.umbrella.com/auth/v2/token
          scopes:
            reports.granularEvents:read: 'Read reports granular events'
            reports.utilities:read: 'Read reports utilities'
            reports.aggregations:read: 'Read reports aggregations'
            reports.summariesByRule:read: 'Read reports for the summaries of the rule'
            reports.customers:read: 'Read reports for the customers'
