openapi: 3.0.1
info:
  title: Cisco Umbrella Service Providers Console API
  version: 2.0.0
  description: Configure the Service Providers console.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.umbrella.com/{basePath}
    variables:
      basePath:
        default: admin/v2

tags:
  - name: Cnames
  - name: Contacts
  - name: Logos
  - name: Umbrella

security:
  - oauthFlow: []

paths:
  '/config/cnames':
    get:
      tags:
        - Cnames
        - Umbrella
      description: List the cname information for the service providers console.
      summary: List Cnames
      operationId: getCnames
      security:
        - oauthFlow:
            - admin.config:read
    post:
      tags:
        - Cnames
        - Umbrella
      description: Add the cname information for the service providers console.
      summary: Create Cname
      operationId: createCname
      security:
        - oauthFlow:
            - admin.config:write
  '/config/cnames/{cnameId}':
    get:
      tags:
        - Cnames
        - Umbrella
      description: Get the cname information for the service providers console.
      summary: Get Cname
      operationId: getCname
      security:
        - oauthFlow:
            - admin.config:read
    put:
      tags:
        - Cnames
        - Umbrella
      description: Update the cname information for the service providers console.
      summary: Update Cname
      operationId: updateCname
      security:
        - oauthFlow:
            - admin.config:write
    delete:
      tags:
        - Cnames
        - Umbrella
      description: Delete a cname for the service providers console.
      operationId: deleteCname
      summary: Delete Cname
      security:
        - oauthFlow:
            - admin.config:write
  '/config/contacts':
    get:
      tags:
        - Contacts
        - Umbrella
      description: List the contacts for the service providers console.
      summary: List Contacts
      operationId: getContacts
      security:
        - oauthFlow:
            - admin.config:read
    post:
      tags:
        - Contacts
        - Umbrella
      description: Create a contact for the service providers console.
      summary: Create Contact
      operationId: createContact
      security:
        - oauthFlow:
            - admin.config:write
  '/config/contacts/{contactId}':
    get:
      tags:
        - Contacts
        - Umbrella
      description: Get a contact for the service providers console.
      summary: Get Contact
      operationId: getContact
      security:
        - oauthFlow:
            - admin.config:read
    put:
      tags:
        - Contacts
        - Umbrella
      description: Update a contact for service providers console.
      summary: Update Contact
      operationId: updateContact
      security:
        - oauthFlow:
            - admin.config:write
    delete:
      tags:
        - Contacts
        - Umbrella
      description: Delete a contact for the service providers console.
      summary: Delete Contact
      operationId: deleteContact
      security:
        - oauthFlow:
            - admin.config:write
  '/config/logos':
    get:
      tags:
        - Logos
        - Umbrella
      description: Get the logos for the service providers console.
      summary: List Logos
      operationId: getLogos
      security:
        - oauthFlow:
            - admin.config:read
    post:
      tags:
        - Logos
        - Umbrella
      description: Create a logo for the service providers console.
      summary: Create Logo
      operationId: createLogo
      security:
        - oauthFlow:
            - admin.config:write
  '/config/logos/{logoId}':

    get:
      tags:
        - Logos
        - Umbrella
      description: Get a logo for the service providers console.
      summary: Get Logo
      operationId: getLogo
      security:
        - oauthFlow:
            - admin.config:read
    put:
      tags:
        - Logos
        - Umbrella
      description: Update a logo for the service providers console.
      summary: Update Logo
      operationId: updateLogo
      security:
        - oauthFlow:
            - admin.config:write
    delete:
      tags:
        - Logos
        - Umbrella
      description: Delete a logo for the service providers console.
      summary: Delete Logo
      operationId: deleteLogo
      security:
        - oauthFlow:
            - admin.config:write
components:

  securitySchemes:
    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.umbrella.com/auth/v2/token
          scopes:
            admin.config:read: 'Read admin config'
            admin.config:write: 'Write admin config'
