openapi: 3.0.1
info:
  title: Cisco Umbrella Users and Roles API
  version: 2.0.0
  description: Manage the Umbrella user accounts and roles.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.umbrella.com/{basePath}
    variables:
      basePath:
        default: admin/v2

security:
  - oauthFlow: []

tags:
  - name: Users
  - name: Roles
  - name: Umbrella

paths:

  '/users':
    post:
      tags:
        - Users
        - Umbrella
      description: |-
        Create an Umbrella user account with a designated role.

        Once a user account is deleted, you can recreate the account through the `POST` operation.
        When you recreate the user account, only set the `email` and `roleId` fields in the Request Body.

        For example: {
          "email": "DEVWKS-22@mailinator.com",
          "roleId": 1
        }

        If you provide all fields for the user account in the Request Body, Umbrella returns an `HTTP/400` (Bad Request) with the
        message: `Email already in use`.
      summary: Create User
      operationId: createUser
      security:
        - oauthFlow:
            - admin.users:write
    get:
      tags:
        - Users
        - Umbrella
      description: List the user accounts in the organization.
      summary: List Users
      operationId: listUsers
      security:
        - oauthFlow:
            - admin.users:read
  '/users/{userId}':
    get:
      tags:
        - Users
        - Umbrella
      description: Get a user account.
      summary: Get User
      operationId: getUser
      security:
        - oauthFlow:
            - admin.users:read
    delete:
      tags:
        - Users
        - Umbrella
      description: Delete a user account.
      summary: Delete User
      operationId: deleteUser
      security:
        - oauthFlow:
            - admin.users:write
  '/roles':
    get:
      tags:
        - Roles
        - Umbrella
      description: List the roles in the organization.
      summary: List Roles
      operationId: listRoles
      security:
        - oauthFlow:
            - admin.roles:read
# passwordresets
  '/passwordResets/{customerId}':
    post:
      tags:
        - Users
        - Umbrella
      description: |-
        Renew the passwords for the user accounts in the child (customer) organization of a provider organization.

        For each email address, Umbrella identifies the user's account and renews the password for the user account.
        Umbrella does not send a renewal request to the user account's email address.

        Once an admin resets the user account password through the `/passwordResets/{customerId}` API endpoint,
        a user can sign into their account on the child (customer) organization's managed console
        and reset the password for their user account.

        The `/passwordResets/{customerId}` API endpoint is only available for parent (provider) organizations
        on the Multi-org or provider console.
      summary: Create Password Resets
      operationId: createPasswordResets
      security:
        - oauthFlow:
          - admin.passwordreset:write
# organizations
  '/organizations':
    get:
      tags:
        - Users
        - Umbrella
      description: |-
        Get information about your provider organizations.
        To query the collection, provide an email address for a member of an Umbrella provider organization.
      summary: Get Information About Organizations
      operationId: getOrganizationInformation
      security:
        - oauthFlow:
          - admin.organizations:read
components:
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.umbrella.com/auth/v2/token
          scopes:
            admin.users:read: 'Read admin users'
            admin.users:write: 'Write admin users'
            admin.roles:read: 'Read admin roles'
            admin.passwordreset:write: 'Write admin passwords'
            admin.organizations:write: 'Read admin organizations'
