openapi: 3.0.1
info:
  title: Cisco Umbrella Network Tunnels API
  description: Manage the network tunnels in the organization.
  version: 2.0.0
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.umbrella.com/{basePath}
    variables:
      basePath:
        default: deployments/v2

security:
  - oauthFlow: []

tags:
  - name: Data Center
  - name: Organization Tunnel
  - name: Debugging
  - name: Umbrella

paths:
  '/datacenters':
    get:
      summary: List Data Centers
      operationId: getDatacenters
      security:
        - oauthFlow:
          - deployments.datacenters:read
      description: |-
        List the information about the IPsec-enabled data centers.
        The data center information includes the IP address and location details.
      tags:
        - Data Center
        - Umbrella
  '/tunnels':
    get:
      summary: List Tunnels
      operationId: listTunnels
      description: List the tunnels for an organization.
      security:
        - oauthFlow:
          - deployments.tunnels:read
      tags:
        - Organization Tunnel
        - Umbrella
    post:
      summary: Create Tunnel
      operationId: addTunnel
      description: Add a new tunnel to the organization.
      security:
        - oauthFlow:
          - deployments.tunnels:write
      tags:
        - Organization Tunnel
        - Umbrella
  '/tunnels/{id}':
    get:
      summary: Get Tunnel
      operationId: getTunnel
      description: Get a specific tunnel.
      security:
        - oauthFlow:
          - deployments.tunnels:read
      tags:
        - Organization Tunnel
        - Umbrella
    put:
      summary: Update Tunnel
      operationId: updateTunnel
      security:
        - oauthFlow:
          - deployments.tunnels:write
      description: |-
        Update the `name`, `siteOriginId`, `networkCIDRs`, and client `deviceType` properties for a tunnel.
        Updates to read-only attributes are ignored.
      tags:
        - Organization Tunnel
        - Umbrella
    delete:
      summary: Delete Tunnel
      operationId: deleteTunnel
      description: Delete a tunnel in the organization.
      security:
        - oauthFlow:
          - deployments.tunnels:write
      tags:
        - Organization Tunnel
        - Umbrella
  '/tunnels/{id}/keys':
    post:
      summary: Update and Rotate Tunnel Credentials
      description: Update and rotate the tunnel credentials.
      tags:
        - Organization Tunnel
        - Umbrella
      operationId: updateTunnelCredentials
      security:
        - oauthFlow:
          - deployments.tunnels:write
  '/tunnels/{id}/policies':
    get:
      summary: List Policies for Tunnel
      operationId: getTunnelPolicies
      security:
        - oauthFlow:
          - deployments.tunnels:read
      description: List the policies that include the network tunnel.
      tags:
        - Organization Tunnel
        - Umbrella
  '/tunnelsState':
    get:
      tags:
        - Debugging
        - Umbrella
      summary: List Tunnel State Information
      operationId: getOrgTunnelState
      security:
        - oauthFlow:
          - deployments.tunnels:read
      description: List the tunnel state information.
  '/tunnels/{id}/state':
    get:
      tags:
        - Debugging
        - Umbrella
      summary: Get Tunnel State
      operationId: getTunnelState
      security:
        - oauthFlow:
          - deployments.tunnels:read
      description: Get the tunnel state information.
  '/tunnels/{id}/events':
    get:
      tags:
        - Debugging
        - Umbrella
      summary: Get Tunnel Error Events
      operationId: getTunnelErrorEvents
      security:
        - oauthFlow:
          - deployments.tunnels:read
      description: Get the recent tunnel error events.
  '/tunnels/{id}/globalEvents/sourceIp/{ip}':
    get:
      tags:
        - Debugging
        - Umbrella
      summary: Get Tunnel Global Error Events
      operationId: getTunnelGlobalErrorEvents
      security:
        - oauthFlow:
          - deployments.tunnels:read
      description: Get the recent global error events.
components:
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.umbrella.com/auth/v2/token
          scopes:
            deployments.tunnels:write: 'Write deployments tunnels'
            deployments.tunnels:read: 'Read deployments tunnels'
            deployments.datacenters:read: 'Read deployments datacenters'
