FROM golang:1.23-bookworm

#RUN echo vscode ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/vscode && chmod 0440 /etc/sudoers.d/vscode
#RUN mkdir /workspaces && chown vscode:vscode /workspaces
#USER vscode
