// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetdestinationsDataSource)
}

// GetdestinationsDataSource implements the getdestinations data source
type GetdestinationsDataSource struct {
	client *apiClient
}

// getdestinationsDataModel represents the data source data model
type getdestinationsDataModel struct {
	Id     types.String `tfsdk:"id"`
	Status types.Object `tfsdk:"status"`
	Meta   types.Object `tfsdk:"meta"`
	Data   types.Set    `tfsdk:"data"`
}

// NewGetdestinationsDataSource creates a new getdestinations data source
func NewGetdestinationsDataSource() datasource.DataSource {
	return &GetdestinationsDataSource{}
}

// Metadata returns the data source type name
func (d *GetdestinationsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getdestinations"
}

// Configure configures the data source with the provider client
func (d *GetdestinationsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetdestinationsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getdestinations data source",
		Attributes: map[string]schema.Attribute{
			"id":     schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"status": schema.StringAttribute{Computed: true, Description: "The status information for the response."},
			"meta":   schema.StringAttribute{Computed: true, Description: "The pagination information for the response."},
			"data":   schema.SetAttribute{Computed: true, Description: "The list of destinations in the destination list.", ElementType: types.StringType},
		},
	}
}

// Read reads the getdestinations data
func (d *GetdestinationsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getdestinationsDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
