// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewTunnelsstateDataSource)
}

// TunnelsstateDataSource implements the tunnelsstate data source
type TunnelsstateDataSource struct {
	client *apiClient
}

// tunnelsstateDataModel represents the data source data model
type tunnelsstateDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewTunnelsstateDataSource creates a new tunnelsstate data source
func NewTunnelsstateDataSource() datasource.DataSource {
	return &TunnelsstateDataSource{}
}

// Metadata returns the data source type name
func (d *TunnelsstateDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_tunnelsstate"
}

// Configure configures the data source with the provider client
func (d *TunnelsstateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *TunnelsstateDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "tunnelsstate data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the tunnelsstate data
func (d *TunnelsstateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config tunnelsstateDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /tunnelsState

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
