// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewAddtagtodevicesResource)
}

// AddtagtodevicesResource implements the addtagtodevices resource
type AddtagtodevicesResource struct {
	client *apiClient
}

// addtagtodevicesModel represents the resource data model
type addtagtodevicesModel struct {
	Id            types.String `tfsdk:"id"`
	RemoveOrigins types.Set    `tfsdk:"remove_origins"`
	TagId         types.Int64  `tfsdk:"tag_id"`
	AddOrigins    types.Set    `tfsdk:"add_origins"`
}

// NewAddtagtodevicesResource creates a new addtagtodevices resource
func NewAddtagtodevicesResource() resource.Resource {
	return &AddtagtodevicesResource{}
}

// Metadata returns the resource type name
func (r *AddtagtodevicesResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_addtagtodevices"
}

// Configure configures the resource with the provider client
func (r *AddtagtodevicesResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *AddtagtodevicesResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "addtagtodevices resource",
		Attributes: map[string]schema.Attribute{
			"id":             schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"remove_origins": schema.SetAttribute{Computed: true, Description: "The list of roaming computers (origin IDs) that have the tag removed.", ElementType: types.StringType},
			"tag_id":         schema.Int64Attribute{Computed: true, Description: "The unique ID of the tag."},
			"add_origins":    schema.SetAttribute{Computed: true, Description: "The list of roaming computers (origin IDs) that have the tag.", ElementType: types.StringType},
		},
	}
}

// Create creates a new addtagtodevices
func (r *AddtagtodevicesResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan addtagtodevicesModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})

	// Make API call
	result, err := r.client.CreateResource(ctx, "/tags/{tagId}/devices", requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create addtagtodevices, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["remove_origins"]; exists && val != nil {
			}
			if val, exists := dataMap["tag_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.TagId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["add_origins"]; exists && val != nil {
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the addtagtodevices
func (r *AddtagtodevicesResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state addtagtodevicesModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the addtagtodevices
func (r *AddtagtodevicesResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan addtagtodevicesModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific update endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No update endpoint configured for addtagtodevices")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the addtagtodevices
func (r *AddtagtodevicesResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state addtagtodevicesModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for addtagtodevices")
}
