// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewTrialstrengthsDataSource)
}

// TrialstrengthsDataSource implements the trialstrengths data source
type TrialstrengthsDataSource struct {
	client *apiClient
}

// trialstrengthsDataModel represents the data source data model
type trialstrengthsDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewTrialstrengthsDataSource creates a new trialstrengths data source
func NewTrialstrengthsDataSource() datasource.DataSource {
	return &TrialstrengthsDataSource{}
}

// Metadata returns the data source type name
func (d *TrialstrengthsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_trialstrengths"
}

// Configure configures the data source with the provider client
func (d *TrialstrengthsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *TrialstrengthsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "trialstrengths data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the trialstrengths data
func (d *TrialstrengthsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config trialstrengthsDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /providers/customers/{customerId}/trialStrengths

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
