// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewUpdatelogoResource)
}

// UpdatelogoResource implements the updatelogo resource
type UpdatelogoResource struct {
	client *apiClient
}

// updatelogoModel represents the resource data model
type updatelogoModel struct {
	Id             types.String `tfsdk:"id"`
	ImageUrl       types.String `tfsdk:"image_url"`
	ModifiedAt     types.Int64  `tfsdk:"modified_at"`
	BrandingTypeId types.Int64  `tfsdk:"branding_type_id"`
	OrganizationId types.String `tfsdk:"organization_id"`
	ImageKey       types.String `tfsdk:"image_key"`
	Token          types.String `tfsdk:"token"`
	CreatedAt      types.Int64  `tfsdk:"created_at"`
	Enabled        types.Bool   `tfsdk:"enabled"`
}

// NewUpdatelogoResource creates a new updatelogo resource
func NewUpdatelogoResource() resource.Resource {
	return &UpdatelogoResource{}
}

// Metadata returns the resource type name
func (r *UpdatelogoResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_updatelogo"
}

// Configure configures the resource with the provider client
func (r *UpdatelogoResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *UpdatelogoResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "updatelogo resource",
		Attributes: map[string]schema.Attribute{
			"id":               schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"image_url":        schema.StringAttribute{Computed: true, Description: "The URL for the logo."},
			"modified_at":      schema.Int64Attribute{Computed: true, Description: "The time when the logo was last modified. The time is specified in milliseconds."},
			"branding_type_id": schema.Int64Attribute{Computed: true, Description: "The ID of the type of branding."},
			"organization_id":  schema.StringAttribute{Computed: true, Description: "The ID of the organization associated with the logo."},
			"image_key":        schema.StringAttribute{Computed: true, Description: "The key for the logo."},
			"token":            schema.StringAttribute{Computed: true, Description: "The randomly generated number for the logo."},
			"created_at":       schema.Int64Attribute{Computed: true, Description: "The time when the logo was created. The time is specified in milliseconds."},
			"enabled":          schema.BoolAttribute{Computed: true, Description: "Specify whether the logo is in use."},
		},
	}
}

// Create creates a new updatelogo
func (r *UpdatelogoResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan updatelogoModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific create endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No create endpoint configured for updatelogo")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the updatelogo
func (r *UpdatelogoResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state updatelogoModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the updatelogo
func (r *UpdatelogoResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan updatelogoModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})

	// Build path with ID
	path := fmt.Sprintf("/config/logos/{logoId}", plan.Id.ValueString())

	// Make API call
	result, err := r.client.UpdateResource(ctx, path, requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update updatelogo, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["image_url"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ImageUrl = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["modified_at"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.ModifiedAt = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["branding_type_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.BrandingTypeId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["organization_id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.OrganizationId = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["image_key"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ImageKey = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["token"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Token = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["created_at"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.CreatedAt = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["enabled"]; exists && val != nil {
				if boolVal, ok := val.(bool); ok {
					plan.Enabled = types.BoolValue(boolVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the updatelogo
func (r *UpdatelogoResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state updatelogoModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for updatelogo")
}
