// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewOrginfoDataSource)
}

// OrginfoDataSource implements the orginfo data source
type OrginfoDataSource struct {
	client *apiClient
}

// orginfoDataModel represents the data source data model
type orginfoDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewOrginfoDataSource creates a new orginfo data source
func NewOrginfoDataSource() datasource.DataSource {
	return &OrginfoDataSource{}
}

// Metadata returns the data source type name
func (d *OrginfoDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_orginfo"
}

// Configure configures the data source with the provider client
func (d *OrginfoDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *OrginfoDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "orginfo data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the orginfo data
func (d *OrginfoDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config orginfoDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /roamingcomputers/orgInfo

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
