// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewTrialconversionsResource)
}

// TrialconversionsResource implements the trialconversions resource
type TrialconversionsResource struct {
	client *apiClient
}

// trialconversionsModel represents the resource data model
type trialconversionsModel struct {
	Id               types.String `tfsdk:"id"`
	Conversionstatus types.String `tfsdk:"conversionStatus"`
}

// NewTrialconversionsResource creates a new trialconversions resource
func NewTrialconversionsResource() resource.Resource {
	return &TrialconversionsResource{}
}

// Metadata returns the resource type name
func (r *TrialconversionsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_trialconversions"
}

// Configure configures the resource with the provider client
func (r *TrialconversionsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *TrialconversionsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "trialconversions resource",
		Attributes: map[string]schema.Attribute{
			"id":               schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"conversionStatus": schema.StringAttribute{Computed: true, Description: "The status of the trial conversion."},
		},
	}
}

// Create creates a new trialconversions
func (r *TrialconversionsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan trialconversionsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement create logic - no specific create endpoint found

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Update updates the trialconversions
func (r *TrialconversionsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan trialconversionsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement update logic using PUT /providers/customers/{customerId}/trialconversions

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the trialconversions
func (r *TrialconversionsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state trialconversionsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement read logic - no specific read endpoint found

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Delete deletes the trialconversions
func (r *TrialconversionsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state trialconversionsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement delete logic - no specific delete endpoint found
}
