// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewSourceipDataSource)
}

// SourceipDataSource implements the sourceip data source
type SourceipDataSource struct {
	client *apiClient
}

// sourceipDataModel represents the data source data model
type sourceipDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewSourceipDataSource creates a new sourceip data source
func NewSourceipDataSource() datasource.DataSource {
	return &SourceipDataSource{}
}

// Metadata returns the data source type name
func (d *SourceipDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_sourceip"
}

// Configure configures the data source with the provider client
func (d *SourceipDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *SourceipDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "sourceip data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the sourceip data
func (d *SourceipDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config sourceipDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /tunnels/{id}/globalEvents/sourceIp/{ip}

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
