// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetapplicationsappdiscoveryDataSource)
}

// GetapplicationsappdiscoveryDataSource implements the getapplicationsappdiscovery data source
type GetapplicationsappdiscoveryDataSource struct {
	client *apiClient
}

// getapplicationsappdiscoveryDataModel represents the data source data model
type getapplicationsappdiscoveryDataModel struct {
	Id          types.String `tfsdk:"id"`
	Items       types.Set    `tfsdk:"items"`
	Currentpage types.Int64  `tfsdk:"currentPage"`
	Totalpages  types.Int64  `tfsdk:"totalPages"`
	Itemscount  types.Int64  `tfsdk:"itemsCount"`
}

// NewGetapplicationsappdiscoveryDataSource creates a new getapplicationsappdiscovery data source
func NewGetapplicationsappdiscoveryDataSource() datasource.DataSource {
	return &GetapplicationsappdiscoveryDataSource{}
}

// Metadata returns the data source type name
func (d *GetapplicationsappdiscoveryDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getapplicationsappdiscovery"
}

// Configure configures the data source with the provider client
func (d *GetapplicationsappdiscoveryDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetapplicationsappdiscoveryDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getapplicationsappdiscovery data source",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"items":       schema.SetAttribute{Computed: true, Description: "The list of application properties.", ElementType: types.StringType},
			"currentPage": schema.Int64Attribute{Computed: true, Description: "The index of the current page in the collection."},
			"totalPages":  schema.Int64Attribute{Computed: true, Description: "The total number of pages in the collection."},
			"itemsCount":  schema.Int64Attribute{Computed: true, Description: "The number of items in the collection."},
		},
	}
}

// Read reads the getapplicationsappdiscovery data
func (d *GetapplicationsappdiscoveryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getapplicationsappdiscoveryDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
