// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewPuttrialconversionsResource)
}

// PuttrialconversionsResource implements the puttrialconversions resource
type PuttrialconversionsResource struct {
	client *apiClient
}

// puttrialconversionsModel represents the resource data model
type puttrialconversionsModel struct {
	Id               types.String `tfsdk:"id"`
	PackageId        types.Int64  `tfsdk:"package_id"`
	ConversionStatus types.String `tfsdk:"conversion_status"`
}

// NewPuttrialconversionsResource creates a new puttrialconversions resource
func NewPuttrialconversionsResource() resource.Resource {
	return &PuttrialconversionsResource{}
}

// Metadata returns the resource type name
func (r *PuttrialconversionsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_puttrialconversions"
}

// Configure configures the resource with the provider client
func (r *PuttrialconversionsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *PuttrialconversionsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "puttrialconversions resource",
		Attributes: map[string]schema.Attribute{
			"id":                schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"package_id":        schema.Int64Attribute{Required: true, Description: "Package Id  Package Name  ::----  `107`  Umbrella Insights   `246`  Umbrella DNS Security Essentials   `248`  Umbrella DNS Security Advantage   `250`  Umbrella SIG Essentials   `252`  Umbrella SIG Advantage"},
			"conversion_status": schema.StringAttribute{Computed: true, Description: "The status of the trial conversion."},
		},
	}
}

// Create creates a new puttrialconversions
func (r *PuttrialconversionsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan puttrialconversionsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific create endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No create endpoint configured for puttrialconversions")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the puttrialconversions
func (r *PuttrialconversionsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state puttrialconversionsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the puttrialconversions
func (r *PuttrialconversionsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan puttrialconversionsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.PackageId.IsNull() {
		requestBody["package_id"] = plan.PackageId.ValueInt64()
	}

	// Build path with ID
	path := fmt.Sprintf("/providers/customers/{customerId}/trialconversions", plan.Id.ValueString())

	// Make API call
	result, err := r.client.UpdateResource(ctx, path, requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update puttrialconversions, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["package_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.PackageId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["conversion_status"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ConversionStatus = types.StringValue(strVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the puttrialconversions
func (r *PuttrialconversionsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state puttrialconversionsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for puttrialconversions")
}
