// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewVirtualappliancesDataSource)
}

// VirtualappliancesDataSource implements the virtualappliances data source
type VirtualappliancesDataSource struct {
	client *apiClient
}

// virtualappliancesDataModel represents the data source data model
type virtualappliancesDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewVirtualappliancesDataSource creates a new virtualappliances data source
func NewVirtualappliancesDataSource() datasource.DataSource {
	return &VirtualappliancesDataSource{}
}

// Metadata returns the data source type name
func (d *VirtualappliancesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_virtualappliances"
}

// Configure configures the data source with the provider client
func (d *VirtualappliancesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *VirtualappliancesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "virtualappliances data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the virtualappliances data
func (d *VirtualappliancesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config virtualappliancesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /virtualappliances/{virtualApplianceId}

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
