// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewVirtualappliancesResource)
}

// VirtualappliancesResource implements the virtualappliances resource
type VirtualappliancesResource struct {
	client *apiClient
}

// virtualappliancesModel represents the resource data model
type virtualappliancesModel struct {
	Id types.String `tfsdk:"id"`
}

// NewVirtualappliancesResource creates a new virtualappliances resource
func NewVirtualappliancesResource() resource.Resource {
	return &VirtualappliancesResource{}
}

// Metadata returns the resource type name
func (r *VirtualappliancesResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_virtualappliances"
}

// Configure configures the resource with the provider client
func (r *VirtualappliancesResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *VirtualappliancesResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "virtualappliances resource",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Resource identifier"},
		},
	}
}

// Create creates a new virtualappliances
func (r *VirtualappliancesResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan virtualappliancesModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement create logic - no specific create endpoint found

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Update updates the virtualappliances
func (r *VirtualappliancesResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan virtualappliancesModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement update logic using PUT /virtualappliances/{virtualApplianceId}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the virtualappliances
func (r *VirtualappliancesResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state virtualappliancesModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement read logic - no specific read endpoint found

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Delete deletes the virtualappliances
func (r *VirtualappliancesResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state virtualappliancesModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement delete logic using DELETE /virtualappliances/{virtualApplianceId}
}
