// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewCreateinternaldomainResource)
}

// CreateinternaldomainResource implements the createinternaldomain resource
type CreateinternaldomainResource struct {
	client *apiClient
}

// createinternaldomainModel represents the resource data model
type createinternaldomainModel struct {
	Id                      types.String `tfsdk:"id"`
	IncludeAllVAs           types.Bool   `tfsdk:"include_all_v_as"`
	IncludeAllMobileDevices types.Bool   `tfsdk:"include_all_mobile_devices"`
	CreatedAt               types.String `tfsdk:"created_at"`
	ModifiedAt              types.String `tfsdk:"modified_at"`
	SiteIds                 types.Set    `tfsdk:"site_ids"`
	Domain                  types.String `tfsdk:"domain"`
	Description             types.String `tfsdk:"description"`
}

// NewCreateinternaldomainResource creates a new createinternaldomain resource
func NewCreateinternaldomainResource() resource.Resource {
	return &CreateinternaldomainResource{}
}

// Metadata returns the resource type name
func (r *CreateinternaldomainResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_createinternaldomain"
}

// Configure configures the resource with the provider client
func (r *CreateinternaldomainResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *CreateinternaldomainResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "createinternaldomain resource",
		Attributes: map[string]schema.Attribute{
			"id":                         schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"include_all_v_as":           schema.BoolAttribute{Computed: true, Description: "Specifies whether to apply the internal domain to all virtual appliances."},
			"include_all_mobile_devices": schema.BoolAttribute{Computed: true, Description: "Specifies whether to apply the internal domain to all mobile devices."},
			"created_at":                 schema.StringAttribute{Computed: true, Description: "The date and time (ISO 8601 timestamp) when the internal domain was created."},
			"modified_at":                schema.StringAttribute{Computed: true, Description: "The date and time (ISO 8601 timestamp) when the internal domain was modified."},
			"site_ids":                   schema.SetAttribute{Computed: true, Description: "The list of site IDs associated with the domain.", ElementType: types.StringType},
			"domain":                     schema.StringAttribute{Computed: true, Description: "The domain name of the internal domain."},
			"description":                schema.StringAttribute{Computed: true, Description: "The description of the internal domain."},
		},
	}
}

// Create creates a new createinternaldomain
func (r *CreateinternaldomainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan createinternaldomainModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})

	// Make API call
	result, err := r.client.CreateResource(ctx, "/internaldomains", requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create createinternaldomain, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["include_all_v_as"]; exists && val != nil {
				if boolVal, ok := val.(bool); ok {
					plan.IncludeAllVAs = types.BoolValue(boolVal)
				}
			}
			if val, exists := dataMap["include_all_mobile_devices"]; exists && val != nil {
				if boolVal, ok := val.(bool); ok {
					plan.IncludeAllMobileDevices = types.BoolValue(boolVal)
				}
			}
			if val, exists := dataMap["created_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.CreatedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["modified_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ModifiedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["site_ids"]; exists && val != nil {
			}
			if val, exists := dataMap["domain"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Domain = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["description"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Description = types.StringValue(strVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the createinternaldomain
func (r *CreateinternaldomainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state createinternaldomainModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the createinternaldomain
func (r *CreateinternaldomainResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan createinternaldomainModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific update endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No update endpoint configured for createinternaldomain")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the createinternaldomain
func (r *CreateinternaldomainResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state createinternaldomainModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for createinternaldomain")
}
