// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetprotocolidentitiesDataSource)
}

// GetprotocolidentitiesDataSource implements the getprotocolidentities data source
type GetprotocolidentitiesDataSource struct {
	client *apiClient
}

// getprotocolidentitiesDataModel represents the data source data model
type getprotocolidentitiesDataModel struct {
	Id    types.String `tfsdk:"id"`
	Items types.Set    `tfsdk:"items"`
}

// NewGetprotocolidentitiesDataSource creates a new getprotocolidentities data source
func NewGetprotocolidentitiesDataSource() datasource.DataSource {
	return &GetprotocolidentitiesDataSource{}
}

// Metadata returns the data source type name
func (d *GetprotocolidentitiesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getprotocolidentities"
}

// Configure configures the data source with the provider client
func (d *GetprotocolidentitiesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetprotocolidentitiesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getprotocolidentities data source",
		Attributes: map[string]schema.Attribute{
			"id":    schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"items": schema.SetAttribute{Computed: true, ElementType: types.StringType},
		},
	}
}

// Read reads the getprotocolidentities data
func (d *GetprotocolidentitiesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getprotocolidentitiesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
