// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewSubscriptiondetailsDataSource)
}

// SubscriptiondetailsDataSource implements the subscriptiondetails data source
type SubscriptiondetailsDataSource struct {
	client *apiClient
}

// subscriptiondetailsDataModel represents the data source data model
type subscriptiondetailsDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewSubscriptiondetailsDataSource creates a new subscriptiondetails data source
func NewSubscriptiondetailsDataSource() datasource.DataSource {
	return &SubscriptiondetailsDataSource{}
}

// Metadata returns the data source type name
func (d *SubscriptiondetailsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_subscriptiondetails"
}

// Configure configures the data source with the provider client
func (d *SubscriptiondetailsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *SubscriptiondetailsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "subscriptiondetails data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the subscriptiondetails data
func (d *SubscriptiondetailsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config subscriptiondetailsDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /providers/customers/{customerId}/subscriptionDetails

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
