// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetapplicationattributesDataSource)
}

// GetapplicationattributesDataSource implements the getapplicationattributes data source
type GetapplicationattributesDataSource struct {
	client *apiClient
}

// getapplicationattributesDataModel represents the data source data model
type getapplicationattributesDataModel struct {
	Id                   types.String `tfsdk:"id"`
	Attributescategories types.Set    `tfsdk:"attributesCategories"`
}

// NewGetapplicationattributesDataSource creates a new getapplicationattributes data source
func NewGetapplicationattributesDataSource() datasource.DataSource {
	return &GetapplicationattributesDataSource{}
}

// Metadata returns the data source type name
func (d *GetapplicationattributesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getapplicationattributes"
}

// Configure configures the data source with the provider client
func (d *GetapplicationattributesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetapplicationattributesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getapplicationattributes data source",
		Attributes: map[string]schema.Attribute{
			"id":                   schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"attributesCategories": schema.SetAttribute{Computed: true, ElementType: types.StringType},
		},
	}
}

// Read reads the getapplicationattributes data
func (d *GetapplicationattributesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getapplicationattributesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
