// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewListsecurewebgatewaydevicesettingsResource)
}

// ListsecurewebgatewaydevicesettingsResource implements the listsecurewebgatewaydevicesettings resource
type ListsecurewebgatewaydevicesettingsResource struct {
	client *apiClient
}

// listsecurewebgatewaydevicesettingsModel represents the resource data model
type listsecurewebgatewaydevicesettingsModel struct {
	Id         types.String `tfsdk:"id"`
	OriginIds  types.Set    `tfsdk:"origin_ids"`
	OriginId   types.Int64  `tfsdk:"origin_id"`
	Name       types.String `tfsdk:"name"`
	Value      types.String `tfsdk:"value"`
	ModifiedAt types.String `tfsdk:"modified_at"`
}

// NewListsecurewebgatewaydevicesettingsResource creates a new listsecurewebgatewaydevicesettings resource
func NewListsecurewebgatewaydevicesettingsResource() resource.Resource {
	return &ListsecurewebgatewaydevicesettingsResource{}
}

// Metadata returns the resource type name
func (r *ListsecurewebgatewaydevicesettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_listsecurewebgatewaydevicesettings"
}

// Configure configures the resource with the provider client
func (r *ListsecurewebgatewaydevicesettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *ListsecurewebgatewaydevicesettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "listsecurewebgatewaydevicesettings resource",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"origin_ids":  schema.SetAttribute{Required: true, Description: "The list of origin IDs. The list can contain 1–100 origin IDs.", ElementType: types.StringType},
			"origin_id":   schema.Int64Attribute{Computed: true, Description: "The origin ID of the device."},
			"name":        schema.StringAttribute{Computed: true, Description: "The name of the device setting."},
			"value":       schema.StringAttribute{Computed: true, Description: "Specifies whether to enable the Secure Web Gateway (SWG) device settings. Valid values are: `0` or `1` where `1` indicates enable."},
			"modified_at": schema.StringAttribute{Computed: true, Description: "The date and time when the settings on the device were modified. The timestamp is in the ISO 8601 date format."},
		},
	}
}

// Create creates a new listsecurewebgatewaydevicesettings
func (r *ListsecurewebgatewaydevicesettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan listsecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.OriginIds.IsNull() {
		requestBody["origin_ids"] = plan.OriginIds.ValueString()
	}

	// Make API call
	result, err := r.client.CreateResource(ctx, "/deviceSettings/SWGEnabled/list", requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create listsecurewebgatewaydevicesettings, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["origin_ids"]; exists && val != nil {
			}
			if val, exists := dataMap["origin_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.OriginId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["name"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Name = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["value"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Value = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["modified_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ModifiedAt = types.StringValue(strVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the listsecurewebgatewaydevicesettings
func (r *ListsecurewebgatewaydevicesettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state listsecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the listsecurewebgatewaydevicesettings
func (r *ListsecurewebgatewaydevicesettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan listsecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific update endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No update endpoint configured for listsecurewebgatewaydevicesettings")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the listsecurewebgatewaydevicesettings
func (r *ListsecurewebgatewaydevicesettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state listsecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for listsecurewebgatewaydevicesettings")
}
