// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetapiusagesummaryDataSource)
}

// GetapiusagesummaryDataSource implements the getapiusagesummary data source
type GetapiusagesummaryDataSource struct {
	client *apiClient
}

// getapiusagesummaryDataModel represents the data source data model
type getapiusagesummaryDataModel struct {
	Id   types.String `tfsdk:"id"`
	Data types.Object `tfsdk:"data"`
}

// NewGetapiusagesummaryDataSource creates a new getapiusagesummary data source
func NewGetapiusagesummaryDataSource() datasource.DataSource {
	return &GetapiusagesummaryDataSource{}
}

// Metadata returns the data source type name
func (d *GetapiusagesummaryDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getapiusagesummary"
}

// Configure configures the data source with the provider client
func (d *GetapiusagesummaryDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetapiusagesummaryDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getapiusagesummary data source",
		Attributes: map[string]schema.Attribute{
			"id":   schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"data": schema.StringAttribute{Computed: true, Description: "The total number of requsts and the counts of the failed and successful requests."},
		},
	}
}

// Read reads the getapiusagesummary data
func (d *GetapiusagesummaryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getapiusagesummaryDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
