// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetdestinationlistsDataSource)
}

// GetdestinationlistsDataSource implements the getdestinationlists data source
type GetdestinationlistsDataSource struct {
	client *apiClient
}

// getdestinationlistsDataModel represents the data source data model
type getdestinationlistsDataModel struct {
	Id     types.String `tfsdk:"id"`
	Status types.Object `tfsdk:"status"`
	Meta   types.Object `tfsdk:"meta"`
	Data   types.Set    `tfsdk:"data"`
}

// NewGetdestinationlistsDataSource creates a new getdestinationlists data source
func NewGetdestinationlistsDataSource() datasource.DataSource {
	return &GetdestinationlistsDataSource{}
}

// Metadata returns the data source type name
func (d *GetdestinationlistsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getdestinationlists"
}

// Configure configures the data source with the provider client
func (d *GetdestinationlistsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetdestinationlistsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getdestinationlists data source",
		Attributes: map[string]schema.Attribute{
			"id":     schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"status": schema.StringAttribute{Computed: true, Description: "The status information for the response."},
			"meta":   schema.StringAttribute{Computed: true, Description: "The pagination information for the response."},
			"data":   schema.SetAttribute{Computed: true, Description: "The list of destination lists.", ElementType: types.StringType},
		},
	}
}

// Read reads the getdestinationlists data
func (d *GetdestinationlistsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getdestinationlistsDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
