// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewApikeysResource)
}

// ApikeysResource implements the apikeys resource
type ApikeysResource struct {
	client *apiClient
}

// apikeysModel represents the resource data model
type apikeysModel struct {
	Id types.String `tfsdk:"id"`
}

// NewApikeysResource creates a new apikeys resource
func NewApikeysResource() resource.Resource {
	return &ApikeysResource{}
}

// Metadata returns the resource type name
func (r *ApikeysResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_apikeys"
}

// Configure configures the resource with the provider client
func (r *ApikeysResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *ApikeysResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "apikeys resource",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Resource identifier"},
		},
	}
}

// Create creates a new apikeys
func (r *ApikeysResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan apikeysModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement create logic using POST /apiKeys

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Update updates the apikeys
func (r *ApikeysResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan apikeysModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement update logic using PATCH /apiKeys/{apiKeyId}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the apikeys
func (r *ApikeysResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state apikeysModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// TODO: Implement read logic - no specific read endpoint found

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Delete deletes the apikeys
func (r *ApikeysResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state apikeysModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement delete logic using DELETE /apiKeys/{apiKeyId}
}
