// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewDeletesecurewebgatewaydevicesettingsResource)
}

// DeletesecurewebgatewaydevicesettingsResource implements the deletesecurewebgatewaydevicesettings resource
type DeletesecurewebgatewaydevicesettingsResource struct {
	client *apiClient
}

// deletesecurewebgatewaydevicesettingsModel represents the resource data model
type deletesecurewebgatewaydevicesettingsModel struct {
	Id        types.String `tfsdk:"id"`
	OriginIds types.Set    `tfsdk:"origin_ids"`
}

// NewDeletesecurewebgatewaydevicesettingsResource creates a new deletesecurewebgatewaydevicesettings resource
func NewDeletesecurewebgatewaydevicesettingsResource() resource.Resource {
	return &DeletesecurewebgatewaydevicesettingsResource{}
}

// Metadata returns the resource type name
func (r *DeletesecurewebgatewaydevicesettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_deletesecurewebgatewaydevicesettings"
}

// Configure configures the resource with the provider client
func (r *DeletesecurewebgatewaydevicesettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *DeletesecurewebgatewaydevicesettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "deletesecurewebgatewaydevicesettings resource",
		Attributes: map[string]schema.Attribute{
			"id":         schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"origin_ids": schema.SetAttribute{Required: true, Description: "The list of origin IDs. The list can contain 1–100 origin IDs.", ElementType: types.StringType},
		},
	}
}

// Create creates a new deletesecurewebgatewaydevicesettings
func (r *DeletesecurewebgatewaydevicesettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan deletesecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.OriginIds.IsNull() {
		requestBody["origin_ids"] = plan.OriginIds.ValueString()
	}

	// Make API call
	result, err := r.client.CreateResource(ctx, "/deviceSettings/SWGEnabled/remove", requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create deletesecurewebgatewaydevicesettings, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["origin_ids"]; exists && val != nil {
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the deletesecurewebgatewaydevicesettings
func (r *DeletesecurewebgatewaydevicesettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state deletesecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the deletesecurewebgatewaydevicesettings
func (r *DeletesecurewebgatewaydevicesettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan deletesecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific update endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No update endpoint configured for deletesecurewebgatewaydevicesettings")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the deletesecurewebgatewaydevicesettings
func (r *DeletesecurewebgatewaydevicesettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state deletesecurewebgatewaydevicesettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for deletesecurewebgatewaydevicesettings")
}
