// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewListvirtualappliancesDataSource)
}

// ListvirtualappliancesDataSource implements the listvirtualappliances data source
type ListvirtualappliancesDataSource struct {
	client *apiClient
}

// listvirtualappliancesDataModel represents the data source data model
type listvirtualappliancesDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewListvirtualappliancesDataSource creates a new listvirtualappliances data source
func NewListvirtualappliancesDataSource() datasource.DataSource {
	return &ListvirtualappliancesDataSource{}
}

// Metadata returns the data source type name
func (d *ListvirtualappliancesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_listvirtualappliances"
}

// Configure configures the data source with the provider client
func (d *ListvirtualappliancesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *ListvirtualappliancesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "listvirtualappliances data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the listvirtualappliances data
func (d *ListvirtualappliancesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config listvirtualappliancesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
