// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewUpdatetunnelResource)
}

// UpdatetunnelResource implements the updatetunnel resource
type UpdatetunnelResource struct {
	client *apiClient
}

// updatetunnelModel represents the resource data model
type updatetunnelModel struct {
	Id                                       types.String `tfsdk:"id"`
	ClientDeviceType                         types.String `tfsdk:"client_device_type"`
	ClientAuthenticationParametersId         types.String `tfsdk:"client_authentication_parameters_id"`
	ClientAuthenticationParametersModifiedAt types.String `tfsdk:"client_authentication_parameters_modified_at"`
	ClientAuthenticationType                 types.String `tfsdk:"client_authentication_type"`
	Name                                     types.String `tfsdk:"name"`
	SiteOriginId                             types.Int64  `tfsdk:"site_origin_id"`
	NetworkCIDRs                             types.Set    `tfsdk:"network_c_i_d_rs"`
	Uri                                      types.String `tfsdk:"uri"`
	CreatedAt                                types.String `tfsdk:"created_at"`
	ModifiedAt                               types.String `tfsdk:"modified_at"`
	TransportProtocol                        types.String `tfsdk:"transport_protocol"`
	ServiceType                              types.String `tfsdk:"service_type"`
}

// NewUpdatetunnelResource creates a new updatetunnel resource
func NewUpdatetunnelResource() resource.Resource {
	return &UpdatetunnelResource{}
}

// Metadata returns the resource type name
func (r *UpdatetunnelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_updatetunnel"
}

// Configure configures the resource with the provider client
func (r *UpdatetunnelResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *UpdatetunnelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "updatetunnel resource",
		Attributes: map[string]schema.Attribute{
			"id":                                  schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"client_device_type":                  schema.StringAttribute{Optional: true, Description: "The type of device from which the tunnel originates. The default value is `other`."},
			"client_authentication_parameters_id": schema.StringAttribute{Computed: true, Description: "The PSK ID. If an IP address is used as the ID, the IP address is returned."},
			"client_authentication_parameters_modified_at": schema.StringAttribute{Computed: true, Description: "The data and time (timestamp) when the tunnel was updated."},
			"client_authentication_type":                   schema.StringAttribute{Optional: true},
			"name":                                         schema.StringAttribute{Required: true, Description: "Display name for the tunnel. The tunnel name is required. The name can't exceed 50 characters in length and can not have any special characters other than spaces and hyphens."},
			"site_origin_id":                               schema.Int64Attribute{Optional: true, Description: "The site origin ID that is associated with the tunnel."},
			"network_c_i_d_rs":                             schema.SetAttribute{Optional: true, Description: "Enter IPv4 ranges and CIDR addresses. If `serviceType` is SIG, add all public and private address ranges used internally by your organization. Overrides Umbrella's default behavior, which allows traffic that is destined for RFC-1918 addresses to return through the tunnel. If `serviceType` is Private Access, this field is required. The 0.0.0.0/0 address range is not allowed.", ElementType: types.StringType},
			"uri":                                          schema.StringAttribute{Computed: true, Description: "Resource URI"},
			"created_at":                                   schema.StringAttribute{Computed: true, Description: "The time when the tunnel was created."},
			"modified_at":                                  schema.StringAttribute{Computed: true, Description: "The data and time (timestamp) when the tunnel was updated."},
			"transport_protocol":                           schema.StringAttribute{Computed: true, Description: "The tunnel transport protocol. The default is IPSec."},
			"service_type":                                 schema.StringAttribute{Computed: true, Description: "The type of service to associate with the tunnel. The default value is `SIG`."},
		},
	}
}

// Create creates a new updatetunnel
func (r *UpdatetunnelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan updatetunnelModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific create endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No create endpoint configured for updatetunnel")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the updatetunnel
func (r *UpdatetunnelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state updatetunnelModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the updatetunnel
func (r *UpdatetunnelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan updatetunnelModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.ClientDeviceType.IsNull() {
		requestBody["client_device_type"] = plan.ClientDeviceType.ValueString()
	}
	if !plan.ClientAuthenticationType.IsNull() {
		requestBody["client_authentication_type"] = plan.ClientAuthenticationType.ValueString()
	}
	if !plan.Name.IsNull() {
		requestBody["name"] = plan.Name.ValueString()
	}
	if !plan.SiteOriginId.IsNull() {
		requestBody["site_origin_id"] = plan.SiteOriginId.ValueInt64()
	}
	if !plan.NetworkCIDRs.IsNull() {
		requestBody["network_c_i_d_rs"] = plan.NetworkCIDRs.ValueString()
	}

	// Build path with ID
	path := fmt.Sprintf("/tunnels/{id}", plan.Id.ValueString())

	// Make API call
	result, err := r.client.UpdateResource(ctx, path, requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update updatetunnel, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["client_device_type"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ClientDeviceType = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["client_authentication_parameters_id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ClientAuthenticationParametersId = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["client_authentication_parameters_modified_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ClientAuthenticationParametersModifiedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["client_authentication_type"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ClientAuthenticationType = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["name"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Name = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["site_origin_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.SiteOriginId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["network_c_i_d_rs"]; exists && val != nil {
			}
			if val, exists := dataMap["uri"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Uri = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["created_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.CreatedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["modified_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ModifiedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["transport_protocol"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.TransportProtocol = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["service_type"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.ServiceType = types.StringValue(strVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the updatetunnel
func (r *UpdatetunnelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state updatetunnelModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for updatetunnel")
}
