// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetapiusageresponsesDataSource)
}

// GetapiusageresponsesDataSource implements the getapiusageresponses data source
type GetapiusageresponsesDataSource struct {
	client *apiClient
}

// getapiusageresponsesDataModel represents the data source data model
type getapiusageresponsesDataModel struct {
	Id    types.String `tfsdk:"id"`
	To    types.String `tfsdk:"to"`
	Count types.Int64  `tfsdk:"count"`
	Items types.Set    `tfsdk:"items"`
	From  types.String `tfsdk:"from"`
}

// NewGetapiusageresponsesDataSource creates a new getapiusageresponses data source
func NewGetapiusageresponsesDataSource() datasource.DataSource {
	return &GetapiusageresponsesDataSource{}
}

// Metadata returns the data source type name
func (d *GetapiusageresponsesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getapiusageresponses"
}

// Configure configures the data source with the provider client
func (d *GetapiusageresponsesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetapiusageresponsesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getapiusageresponses data source",
		Attributes: map[string]schema.Attribute{
			"id":    schema.StringAttribute{Computed: true, Description: "Data source identifier"},
			"to":    schema.StringAttribute{Computed: true, Description: "The date and time where to stop reading in the collection."},
			"count": schema.Int64Attribute{Computed: true, Description: "The total number of API requests."},
			"items": schema.SetAttribute{Computed: true, Description: "The list of information about API responses for the API requests.", ElementType: types.StringType},
			"from":  schema.StringAttribute{Computed: true, Description: "The date and time where to start reading in the collection."},
		},
	}
}

// Read reads the getapiusageresponses data
func (d *GetapiusageresponsesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getapiusageresponsesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
