// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewNetworkdevicesDataSource)
}

// NetworkdevicesDataSource implements the networkdevices data source
type NetworkdevicesDataSource struct {
	client *apiClient
}

// networkdevicesDataModel represents the data source data model
type networkdevicesDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewNetworkdevicesDataSource creates a new networkdevices data source
func NewNetworkdevicesDataSource() datasource.DataSource {
	return &NetworkdevicesDataSource{}
}

// Metadata returns the data source type name
func (d *NetworkdevicesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_networkdevices"
}

// Configure configures the data source with the provider client
func (d *NetworkdevicesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *NetworkdevicesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "networkdevices data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the networkdevices data
func (d *NetworkdevicesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config networkdevicesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement read logic using GET /networkdevices

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
