// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewUpdatemanagedprovidercustomerResource)
}

// UpdatemanagedprovidercustomerResource implements the updatemanagedprovidercustomer resource
type UpdatemanagedprovidercustomerResource struct {
	client *apiClient
}

// updatemanagedprovidercustomerModel represents the resource data model
type updatemanagedprovidercustomerModel struct {
	Id           types.String `tfsdk:"id"`
	CustomerName types.String `tfsdk:"customer_name"`
	Seats        types.Int64  `tfsdk:"seats"`
	CustomerId   types.Int64  `tfsdk:"customer_id"`
}

// NewUpdatemanagedprovidercustomerResource creates a new updatemanagedprovidercustomer resource
func NewUpdatemanagedprovidercustomerResource() resource.Resource {
	return &UpdatemanagedprovidercustomerResource{}
}

// Metadata returns the resource type name
func (r *UpdatemanagedprovidercustomerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_updatemanagedprovidercustomer"
}

// Configure configures the resource with the provider client
func (r *UpdatemanagedprovidercustomerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *UpdatemanagedprovidercustomerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "updatemanagedprovidercustomer resource",
		Attributes: map[string]schema.Attribute{
			"id":            schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"customer_name": schema.StringAttribute{Required: true, Description: "The customer's organization name."},
			"seats":         schema.Int64Attribute{Required: true, Description: "The number of users."},
			"customer_id":   schema.Int64Attribute{Computed: true, Description: "The ID of the customer."},
		},
	}
}

// Create creates a new updatemanagedprovidercustomer
func (r *UpdatemanagedprovidercustomerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan updatemanagedprovidercustomerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific create endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No create endpoint configured for updatemanagedprovidercustomer")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the updatemanagedprovidercustomer
func (r *UpdatemanagedprovidercustomerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state updatemanagedprovidercustomerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the updatemanagedprovidercustomer
func (r *UpdatemanagedprovidercustomerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan updatemanagedprovidercustomerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.CustomerName.IsNull() {
		requestBody["customer_name"] = plan.CustomerName.ValueString()
	}
	if !plan.Seats.IsNull() {
		requestBody["seats"] = plan.Seats.ValueInt64()
	}

	// Build path with ID
	path := fmt.Sprintf("/managed/customers/{customerId}", plan.Id.ValueString())

	// Make API call
	result, err := r.client.UpdateResource(ctx, path, requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update updatemanagedprovidercustomer, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["customer_name"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.CustomerName = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["seats"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.Seats = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["customer_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.CustomerId = types.Int64Value(int64(floatVal))
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the updatemanagedprovidercustomer
func (r *UpdatemanagedprovidercustomerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state updatemanagedprovidercustomerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for updatemanagedprovidercustomer")
}
