// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this data source with the generated resource registry
func init() {
	RegisterGeneratedDataSource(NewGetallnetworkdevicesDataSource)
}

// GetallnetworkdevicesDataSource implements the getallnetworkdevices data source
type GetallnetworkdevicesDataSource struct {
	client *apiClient
}

// getallnetworkdevicesDataModel represents the data source data model
type getallnetworkdevicesDataModel struct {
	Id types.String `tfsdk:"id"`
}

// NewGetallnetworkdevicesDataSource creates a new getallnetworkdevices data source
func NewGetallnetworkdevicesDataSource() datasource.DataSource {
	return &GetallnetworkdevicesDataSource{}
}

// Metadata returns the data source type name
func (d *GetallnetworkdevicesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "umbrella_getallnetworkdevices"
}

// Configure configures the data source with the provider client
func (d *GetallnetworkdevicesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected DataSource Configure Type", "Expected *apiClient")
		return
	}

	d.client = client
}

// Schema defines the data source schema
func (d *GetallnetworkdevicesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "getallnetworkdevices data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "Data source identifier"},
		},
	}
}

// Read reads the getallnetworkdevices data
func (d *GetallnetworkdevicesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config getallnetworkdevicesDataModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read logic is now implemented in the template

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
