// Code generated by terraform-provider-umbrella generator. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// init registers this resource with the generated resource registry
func init() {
	RegisterGeneratedResource(NewUpdatenetworkResource)
}

// UpdatenetworkResource implements the updatenetwork resource
type UpdatenetworkResource struct {
	client *apiClient
}

// updatenetworkModel represents the resource data model
type updatenetworkModel struct {
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	IpAddress    types.String `tfsdk:"ip_address"`
	PrefixLength types.Int64  `tfsdk:"prefix_length"`
	IsDynamic    types.Bool   `tfsdk:"is_dynamic"`
	CreatedAt    types.String `tfsdk:"created_at"`
	OriginId     types.Int64  `tfsdk:"origin_id"`
	IsVerified   types.Bool   `tfsdk:"is_verified"`
}

// NewUpdatenetworkResource creates a new updatenetwork resource
func NewUpdatenetworkResource() resource.Resource {
	return &UpdatenetworkResource{}
}

// Metadata returns the resource type name
func (r *UpdatenetworkResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "umbrella_updatenetwork"
}

// Configure configures the resource with the provider client
func (r *UpdatenetworkResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*apiClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *apiClient")
		return
	}

	r.client = client
}

// Schema defines the resource schema
func (r *UpdatenetworkResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "updatenetwork resource",
		Attributes: map[string]schema.Attribute{
			"id":            schema.StringAttribute{Computed: true, Description: "Resource identifier"},
			"name":          schema.StringAttribute{Required: true, Description: "The name of the network."},
			"ip_address":    schema.StringAttribute{Optional: true, Description: "The IP address of the network."},
			"prefix_length": schema.Int64Attribute{Optional: true, Description: "The length of the prefix. Set a prefix length that is greater than 28 and less than 33."},
			"is_dynamic":    schema.BoolAttribute{Required: true, Description: "Specifies whether the IP address is dynamic."},
			"created_at":    schema.StringAttribute{Computed: true, Description: "The date and time (timestamp) when the network was created."},
			"origin_id":     schema.Int64Attribute{Computed: true, Description: "The origin ID."},
			"is_verified":   schema.BoolAttribute{Computed: true, Description: "Specifies whether the network is verified."},
		},
	}
}

// Create creates a new updatenetwork
func (r *UpdatenetworkResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan updatenetworkModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific create endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No create endpoint configured for updatenetwork")
	return

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the updatenetwork
func (r *UpdatenetworkResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state updatenetworkModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// No specific read endpoint found - return current state
	// This is a no-op read that just returns the current state

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the updatenetwork
func (r *UpdatenetworkResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan updatenetworkModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Create request body from plan
	requestBody := make(map[string]interface{})
	if !plan.Name.IsNull() {
		requestBody["name"] = plan.Name.ValueString()
	}
	if !plan.IpAddress.IsNull() {
		requestBody["ip_address"] = plan.IpAddress.ValueString()
	}
	if !plan.PrefixLength.IsNull() {
		requestBody["prefix_length"] = plan.PrefixLength.ValueInt64()
	}
	if !plan.IsDynamic.IsNull() {
		requestBody["is_dynamic"] = plan.IsDynamic.ValueBool()
	}

	// Build path with ID
	path := fmt.Sprintf("/networks/{networkId}", plan.Id.ValueString())

	// Make API call
	result, err := r.client.UpdateResource(ctx, path, requestBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update updatenetwork, got error: %s", err))
		return
	}

	// Update state with response data
	if result.Data != nil {
		if dataMap, ok := result.Data.(map[string]interface{}); ok {
			if val, exists := dataMap["id"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Id = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["name"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.Name = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["ip_address"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.IpAddress = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["prefix_length"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.PrefixLength = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["is_dynamic"]; exists && val != nil {
				if boolVal, ok := val.(bool); ok {
					plan.IsDynamic = types.BoolValue(boolVal)
				}
			}
			if val, exists := dataMap["created_at"]; exists && val != nil {
				if strVal, ok := val.(string); ok {
					plan.CreatedAt = types.StringValue(strVal)
				}
			}
			if val, exists := dataMap["origin_id"]; exists && val != nil {
				if floatVal, ok := val.(float64); ok {
					plan.OriginId = types.Int64Value(int64(floatVal))
				}
			}
			if val, exists := dataMap["is_verified"]; exists && val != nil {
				if boolVal, ok := val.(bool); ok {
					plan.IsVerified = types.BoolValue(boolVal)
				}
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the updatenetwork
func (r *UpdatenetworkResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state updatenetworkModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No specific delete endpoint found
	resp.Diagnostics.AddError("Configuration Error", "No delete endpoint configured for updatenetwork")
}
